# TODO: need to reverse this by length
ncaa_college_teams = [
    "Abilene Christian",
    "Alabama A&M",
    "Alabama State",
    "Alcorn State",
    "American",
    "Appalachian State",
    "Arizona State",
    "Arkansas State",
    "Auburn",
    "Austin Peay State",
    "Ball State",
    "Baylor",
    "Bellarmine",
    "Belmont",
    "Bethune-Cookman",
    "Boise State",
    "Boston College",
    "Boston U",
    "Bowling Green State",
    "Bradley",
    "BYU",  # Brigham Young University
    "Brown",
    "Bryant",
    "Bucknell",
    "Butler",
    "California Baptist",
    "California Polytechnic State – San Luis Obispo",
    "California State – Bakersfield",
    "California State – Fresno",
    "California State – Fullerton",
    "California State – Long Beach",
    "California State – Northridge",
    "California State – Sacramento",
    "Campbell",
    "Canisius College",
    "Central Connecticut State",
    "Central Michigan",
    "Charleston Southern",
    "Chicago State",
    "Clemson",
    "Cleveland State",
    "Coastal Carolina",
    "Colgate",
    "College of Charleston",
    "College of the Holy Cross",
    "Colorado State",
    "Columbia",
    "Coppin State",
    "Cornell",
    "Creighton",
    "Dartmouth College",
    "Davidson College",
    "Delaware State",
    "DePaul",
    "Drake",
    "Drexel",
    "Duke",
    "Duquesne",
    "East Carolina",
    "East Tenn State",
    "Eastern Illinois",
    "Eastern Kentucky",
    "Eastern Michigan",
    "Eastern Washington",
    "Elon",
    "Fairfield",
    "Fairleigh Dickinson",
    "Florida A&M",
    "Florida Atlantic",
    "Florida Gulf Coast",
    "Florida International",
    "Florida State",
    "Fordham",
    "Furman",
    "Gardner-Webb",
    "George Mason",
    "George Washington",
    "Georgetown",
    "Georgia Southern",
    "Georgia State",
    "Georgia Tech",
    "Gonzaga",
    "Grambling State",
    "Grand Canyon",
    "Hamline",
    "Hampton",
    "Harvard",
    "High Point",
    "Hofstra",
    "Houston Christian",
    "Howard",
    "Idaho State",
    "Illinois State",
    "Indiana State",
    "Indiana",
    "IUPUI",  # "Indiana-Purdue – Indianapolis ()",
    "Iona",
    "Iowa State",
    "Jackson State",
    "Jacksonville State",
    "Jacksonville",
    "James Madison",
    "Kansas State",
    "Kennesaw State",
    "Kent State",
    "La Salle",
    "Lafayette College",
    "Lamar",
    "Lehigh",
    "Liberty",
    "Lindenwood",
    "Lipscomb",
    "Long Island",
    "Longwood",
    "Louisiana State (LSU)",
    "Louisiana Tech",
    "Louisville",
    "Loyola Marymount",
    "Loyola Chicago",
    "Loyola Maryland",
    "Manhattan College",
    "Marist College",
    "Marquette",
    "Marshall",
    "McNeese State",
    "Mercer",
    "Merrimack College",
    "Miami",
    "Michigan State",
    "Middle Tennessee State",
    "Mississippi State",
    "Mississippi Valley State",
    "Missouri State",
    "Monmouth",
    "Montana State",
    "Morehead State",
    "Morgan State",
    "Mount St. Mary's",
    "Murray State",
    "New Jersey Institute of Technology",
    "New Mexico State",
    "Niagara",
    "Nicholls State",
    "Norfolk State",
    "North Carolina A&T State",
    "North Carolina Central",
    "North Carolina State",
    "North Dakota State",
    "Northeastern",
    "Northern Arizona",
    "Northern Illinois",
    "Northern Kentucky",
    "Northwestern State of Louisiana",
    "Northwestern",
    "Oakland",
    "Ohio State",
    "Ohio",
    "Oklahoma State",
    "Old Dominion",
    "Oral Roberts",
    "Oregon State",
    "Penn State",
    "Pepperdine",
    "Portland State",
    "Prairie View A&M",
    "Presbyterian College",
    "Princeton",
    "Providence College",
    "Purdue",
    "Purdue – Fort Wayne",
    "Queens of Charlotte",
    "Quinnipiac",
    "Radford",
    "Rice",
    "Rider",
    "Robert Morris – Pennsylvania",
    "Rutgers",
    "Sacred Heart",
    "Saint Francis",
    "Saint Joseph's",
    "Saint Louis",
    "Saint Mary's College of California",
    "Saint Peter's",
    "Sam Houston State",
    "Samford",
    "San Diego State",
    "San Jose State",
    "Santa Clara",
    "Seattle",
    "Seton Hall",
    "Siena College",
    "South Carolina State",
    "South Dakota State",
    "Southeast Missouri State",
    "Southeastern Louisiana",
    "Southern Illinois Carbondale",
    "Southern Illinois Edwardsville",
    "Southern Methodist – SMU",
    "Southern A&M College",
    "Southern Utah",
    "St. Bonaventure",
    "St. Francis College",
    "St. John's – New York",
    "Stanford",
    "Stephen F Austin State",
    "Stetson",
    "Stonehill College",
    "SUNY Binghamton",
    "SUNY Stony Brook",
    "SUNY at Albany",
    "SUNY at Buffalo",
    "Syracuse",
    "Tarleton State",
    "Temple",
    "Tennessee State",
    "Texas A&M Corpus",
    "Texas",
    "Texas A&M",
    "Texas A&M Commerce",
    "Texas Christian",
    "Texas Southern",
    "Texas State",
    "Texas Tech",
    "The Citadel",
    "Towson",
    "Troy",
    "Tulane",
    "United States Air Force Academy",
    "United States Military Academy",
    "United States Naval Academy",
    "Akron",
    "Alabama",
    "Alabama – Birmingham",
    "Arizona",
    "Arkansas",
    "Arkansas at Little Rock",
    "Arkansas at Pine Bluff",
    "California – Berkeley",
    "California – Davis",
    "California – Irvine",
    "California – Los Angeles – UCLA",
    "California – Riverside",
    "California – San Diego",
    "California – Santa Barbara",
    "Central Arkansas",
    "Central Florida",
    "Central Florida",
    "Cincinnati",
    "Colorado – Boulder",
    "Connecticut",
    "Dayton",
    "Delaware",
    "Denver",
    "Detroit Mercy",
    "Evansville",
    "Florida",
    "Georgia",
    "Hawaii at Manoa",
    "Houston",
    "Idaho",
    "Illinois",
    "Illinois at Chicago",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Louisiana – Monroe",
    "Louisville",
    "Maine",
    "Maryland",
    "Maryland – Baltimore County",
    "Maryland Eastern Shore",
    "Massachusetts – Amherst",
    "Massachusetts – Lowell",
    "Memphis",
    "Miami",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Missouri – Kansas City",
    "Montana",
    "Nebraska",
    "Nebraska at Omaha",
    "Nevada – Las Vegas",
    "Nevada – Reno",
    "New Hampshire",
    "New Mexico",
    "New Orleans",
    "North Alabama",
    "North Carolina – Greensboro",
    "North Carolina – Wilmington",
    "North Carolina Asheville",
    "North Carolina at Chapel Hill",
    "North Carolina at Charlotte",
    "North Dakota",
    "North Florida",
    "North Texas",
    "Northern Colorado",
    "Northern Iowa",
    "Notre Dame",
    "Oklahoma",
    "Oregon",
    "Pennsylvania – Penn",
    "Pittsburgh",
    "Portland",
    "Rhode Island",
    "Richmond",
    "San Diego",
    "San Francisco",
    "South Alabama",
    "South Carolina",
    "South Carolina – Upstate",
    "South Dakota",
    "South Florida",
    "Southern California",
    "Southern Mississippi",
    "St.Thomas – Minnesota",
    "Tennessee",
    "Tennessee – Chattanooga",
    "Tennessee – Martin",
    "Texas – Arlington",
    "Texas – Austin",
    "Texas – El Paso",
    "Texas – Rio Grande Valley",
    "Texas – San Antonio",
    "Toledo",
    "Tulsa",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "Wisconsin",
    "Wisconsin – Green Bay",
    "Wisconsin – Milwaukee",
    "Wyoming",
    "Utah State",
    "Utah Tech (Formerly Dixie State)",
    "Utah Valley",
    "Valparaiso",
    "Vanderbilt",
    "Villanova",
    "Virginia Commonwealth",
    "Virginia Military Institute – VMI",
    "Virginia Tech",
    "Wagner College",
    "Wake Forest",
    "Washington State",
    "Weber State",
    "West Virginia",
    "Western Carolina",
    "Western Illinois",
    "Western Kentucky",
    "Western Michigan",
    "Wichita State",
    "William & Mary",
    "Wisconsin",
    "Winthrop",
    "Wofford College",
    "Wright State",
    "Xavier",
    "Yale",
    "Youngstown State",
    # below here added from 'unrecognized names' output
    "Holy Cross",
    "New Orleans State",
    "Dayton",
    "Davidson",
    "Wisc Milwaukee",
    "Ark Pine Bluff",
    "North Carolina",
    "Hou Christian",
    "Kennesaw St",
    "Evansville",
    "SE Louisiana-Commerce",
    "Grambling",
    "Bethune Cookman",
    "Incarnate Word",
    "Detroit",
    "Robert Morris",
    "USC Upstate",
    "Buffalo",
    "Wofford",
    "Kansas",
    "Navy",
    "Oklahoma",
    "Cincinnati",
    "Tennessee Tech",
    "Notre Dame",
    "TCU",
    "Air Force",
    "VMI",
    "Southern",
    "Army",
    "SE Louisiana",
    "Texas A&M-Commerce",
    "Presbyterian",
    "NC Asheville",
    "East Tenn State",
    "Chattanooga",
    "Nevada",
    "Massachusetts",
    "LSU",
    "Northwestern State",
    "St. Johns",
    "Providence",
    "BYU",
    "Queens NC",
]
