# TODO: need to reverse this by length
ncaa_college_teams = [
    "Abilene Christian",
    "Alabama A&M",
    "Alabama State",
    "Alcorn State",
    "American",
    "Appalachian State",
    "Arizona State",
    "Arkansas State",
    "Auburn",
    "Austin Peay State",
    "Ball State",
    "Baylor",
    "Bellarmine",
    "Belmont",
    "Bethune-Cookman",
    "Boise State",
    "Boston College",
    "Boston U",
    "Bowling Green State",
    "Bradley",
    "Brigham Young",
    "Brown",
    "Bryant",
    "Bucknell",
    "Butler",
    "California Baptist",
    "California Polytechnic State – San Luis Obispo",
    "California State – Bakersfield",
    "California State – Fresno",
    "California State – Fullerton",
    "California State – Long Beach",
    "California State – Northridge",
    "California State – Sacramento",
    "Campbell",
    "Canisius College",
    "Central Connecticut State",
    "Central Michigan",
    "Charleston Southern",
    "Chicago State",
    "Clemson",
    "Cleveland State",
    "Coastal Carolina",
    "Colgate",
    "College of Charleston",
    "College of the Holy Cross",
    "Colorado State",
    "Columbia",
    "Coppin State",
    "Cornell",
    "Creighton",
    "Dartmouth College",
    "Davidson College",
    "Delaware State",
    "DePaul",
    "Drake",
    "Drexel",
    "Duke",
    "Duquesne",
    "East Carolina",
    "East Tennessee State",
    "Eastern Illinois",
    "Eastern Kentucky",
    "Eastern Michigan",
    "Eastern Washington",
    "Elon",
    "Fairfield",
    "Fairleigh Dickinson",
    "Florida A&M",
    "Florida Atlantic",
    "Florida Gulf Coast",
    "Florida International",
    "Florida State",
    "Fordham",
    "Furman",
    "Gardner-Webb",
    "George Mason",
    "George Washington",
    "Georgetown",
    "Georgia Southern",
    "Georgia State",
    "Georgia Tech",
    "Gonzaga",
    "Grambling State",
    "Grand Canyon",
    "Hamline",
    "Hampton",
    "Harvard",
    "High Point",
    "Hofstra",
    "Houston Christian",
    "Howard",
    "Idaho State",
    "Illinois State",
    "Indiana State",
    "Indiana",
    "IUPUI",  # "Indiana-Purdue – Indianapolis ()",
    "Iona",
    "Iowa State",
    "Jackson State",
    "Jacksonville State",
    "Jacksonville",
    "James Madison",
    "Kansas State",
    "Kennesaw State",
    "Kent State",
    "La Salle",
    "Lafayette College",
    "Lamar",
    "Lehigh",
    "Liberty",
    "Lindenwood",
    "Lipscomb",
    "Long Island",
    "Longwood",
    "Louisiana State (LSU)",
    "Louisiana Tech",
    "Loyola Marymount",
    "Loyola Chicago",
    "Loyola Maryland",
    "Manhattan College",
    "Marist College",
    "Marquette",
    "Marshall",
    "McNeese State",
    "Mercer",
    "Merrimack College",
    "Miami",
    "Michigan State",
    "Middle Tennessee State",
    "Mississippi State",
    "Mississippi Valley State",
    "Missouri State",
    "Monmouth",
    "Montana State",
    "Morehead State",
    "Morgan State",
    "Mount St. Mary's",
    "Murray State",
    "New Jersey Institute of Technology",
    "New Mexico State",
    "Niagara",
    "Nicholls State",
    "Norfolk State",
    "North Carolina A&T State",
    "North Carolina Central",
    "North Carolina State",
    "North Dakota State",
    "Northeastern",
    "Northern Arizona",
    "Northern Illinois",
    "Northern Kentucky",
    "Northwestern State of Louisiana",
    "Northwestern",
    "Oakland",
    "Ohio State",
    "Ohio",
    "Oklahoma State",
    "Old Dominion",
    "Oral Roberts",
    "Oregon State",
    "Penn State",
    "Pepperdine",
    "Portland State",
    "Prairie View A&M",
    "Presbyterian College",
    "Princeton",
    "Providence College",
    "Purdue",
    "Purdue – Fort Wayne",
    "Queens of Charlotte",
    "Quinnipiac",
    "Radford",
    "Rice",
    "Rider",
    "Robert Morris – Pennsylvania",
    "Rutgers",
    "Sacred Heart",
    "Saint Francis",
    "Saint Joseph's",
    "Saint Louis",
    "Saint Mary's College of California",
    "Saint Peter's",
    "Sam Houston State",
    "Samford",
    "San Diego State",
    "San Jose State",
    "Santa Clara",
    "Seattle",
    "Seton Hall",
    "Siena College",
    "South Carolina State",
    "South Dakota State",
    "Southeast Missouri State",
    "Southeastern Louisiana",
    "Southern Illinois Carbondale",
    "Southern Illinois Edwardsville",
    "Southern Methodist – SMU",
    "Southern A&M College",
    "Southern Utah",
    "St. Bonaventure",
    "St. Francis College",
    "St. John's – New York",
    "Stanford",
    "Stephen F Austin State",
    "Stetson",
    "Stonehill College",
    "SUNY Binghamton",
    "SUNY Stony Brook",
    "SUNY at Albany",
    "SUNY at Buffalo",
    "Syracuse",
    "Tarleton State",
    "Temple",
    "Tennessee State",
    "Texas A&M Corpus",
    "Texas",
    "Texas A&M",
    "Texas A&M Commerce",
    "Texas Christian",
    "Texas Southern",
    "Texas State",
    "Texas Tech",
    "The Citadel",
    "Towson",
    "Troy",
    "Tulane",
    "United States Air Force Academy",
    "United States Military Academy",
    "United States Naval Academy",
    "University of Akron",
    "University of Alabama",
    "University of Alabama – Birmingham",
    "University of Arizona",
    "University of Arkansas",
    "University of Arkansas at Little Rock",
    "University of Arkansas at Pine Bluff",
    "University of California – Berkeley",
    "University of California – Davis",
    "University of California – Irvine",
    "University of California – Los Angeles – UCLA",
    "University of California – Riverside",
    "University of California – San Diego",
    "University of California – Santa Barbara",
    "University of Central Arkansas",
    "University of Central Florida",
    "University of Central Florida",
    "University of Cincinnati",
    "University of Colorado – Boulder",
    "University of Connecticut",
    "University of Dayton",
    "University of Delaware",
    "University of Denver",
    "University of Detroit Mercy",
    "University of Evansville",
    "University of Florida",
    "University of Georgia",
    "University of Hawaii at Manoa",
    "University of Houston",
    "University of Idaho",
    "University of Illinois",
    "University of Illinois at Chicago",
    "University of Iowa",
    "University of Kansas",
    "University of Kentucky",
    "University of Louisiana",
    "University of Louisiana – Monroe",
    "University of Louisville",
    "University of Maine",
    "University of Maryland",
    "University of Maryland – Baltimore County",
    "University of Maryland Eastern Shore",
    "University of Massachusetts – Amherst",
    "University of Massachusetts – Lowell",
    "University of Memphis",
    "University of Miami",
    "University of Michigan",
    "University of Minnesota",
    "University of Mississippi",
    "University of Missouri",
    "University of Missouri – Kansas City",
    "University of Montana",
    "University of Nebraska",
    "University of Nebraska at Omaha",
    "University of Nevada – Las Vegas",
    "University of Nevada – Reno",
    "University of New Hampshire",
    "University of New Mexico",
    "University of New Orleans",
    "University of North Alabama",
    "University of North Carolina – Greensboro",
    "University of North Carolina – Wilmington",
    "University of North Carolina Asheville",
    "University of North Carolina at Chapel Hill",
    "University of North Carolina at Charlotte",
    "University of North Dakota",
    "University of North Florida",
    "University of North Texas",
    "University of Northern Colorado",
    "University of Northern Iowa",
    "University of Notre Dame",
    "University of Oklahoma",
    "University of Oregon",
    "University of Pennsylvania – Penn",
    "University of Pittsburgh",
    "University of Portland",
    "University of Rhode Island",
    "University of Richmond",
    "University of San Diego",
    "University of San Francisco",
    "University of South Alabama",
    "University of South Carolina",
    "University of South Carolina – Upstate",
    "University of South Dakota",
    "University of South Florida",
    "University of Southern California",
    "University of Southern Mississippi",
    "University of St.Thomas – Minnesota",
    "University of Tennessee",
    "University of Tennessee – Chattanooga",
    "University of Tennessee – Martin",
    "University of Texas – Arlington",
    "University of Texas – Arlington",
    "University of Texas – Austin",
    "University of Texas – El Paso",
    "University of Texas – Rio Grande Valley",
    "University of Texas – San Antonio",
    "University of the Incarnate Word",
    "University of the Pacific",
    "University of Toledo",
    "University of Tulsa",
    "University of Utah",
    "University of Vermont",
    "University of Virginia",
    "University of Washington",
    "University of Wisconsin",
    "University of Wisconsin – Green Bay",
    "University of Wisconsin – Milwaukee",
    "University of Wyoming",
    "Utah State",
    "Utah Tech (Formerly Dixie State)",
    "Utah Valley",
    "Valparaiso",
    "Vanderbilt",
    "Villanova",
    "Virginia Commonwealth",
    "Virginia Military Institute – VMI",
    "Virginia Tech",
    "Wagner College",
    "Wake Forest",
    "Washington State",
    "Weber State",
    "West Virginia",
    "Western Carolina",
    "Western Illinois",
    "Western Kentucky",
    "Western Michigan",
    "Wichita State",
    "William & Mary",
    "Winthrop",
    "Wofford College",
    "Wright State",
    "Xavier",
    "Yale",
    "Youngstown State",
    # below here added from 'unrecognized names' output
    "Holy Cross",
    "New Orleans State",
    "Dayton",
    "Davidson",
    "Wisc Milwaukee",
    "Ark Pine Bluff",
    "North Carolina",
    "Hou Christian",
    "Kennesaw St",
    "Evansville",
    "SE Louisiana-Commerce",
    "Grambling",
    "Bethune Cookman",
    "Incarnate Word",
    "Detroit",
    "Robert Morris",
    "USC Upstate",
    "Buffalo",
    "Wofford",
    "Kansas",
    "Navy",
    "Oklahoma",
    "Cincinnati",
    "Tennessee Tech",
    "Notre Dame",
    "TCU",
    "Air Force",
    "VMI",
    "Southern",
    "Army",

]
