#!/usr/bin/env python3
"""
NHL Analytics Database Manager

This module handles the creation and population of the NHL analytics database
from CSV files generated by the NST scraper.

Design principles:
- Normalized schema for data integrity
- Optimized for analytical queries and simulations
- Handles incremental updates
- Type safety and data validation
"""

import sqlite3
import csv
import os
import re
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Tuple, Optional, Any
from dataclasses import dataclass


@dataclass
class GameInfo:
    """Parsed game information from filename"""
    away_team: str
    home_team: str
    nst_game_id: str
    team_name: str
    category: str
    situation: str


class NHLDatabaseManager:
    """Manages the NHL analytics SQLite database"""

    def __init__(self, db_path: str = "nhl_analytics.db", player_ids_file: str = "player_ids.txt"):
        """
        Initialize database manager

        Args:
            db_path: Path to SQLite database file
            player_ids_file: Path to player IDs mapping file
        """
        self.db_path = db_path
        self.player_ids_file = player_ids_file
        self.conn: Optional[sqlite3.Connection] = None
        self.cursor: Optional[sqlite3.Cursor] = None

        # Mapping of situation codes to IDs (loaded from DB)
        self.situation_map: Dict[str, int] = {}
        self.team_map: Dict[str, int] = {}
        self.player_map: Dict[Tuple[str, str], str] = {}  # (name, position) -> nhl_player_id

        # NHL player ID mapping (name -> nhl_id)
        self.nhl_player_ids: Dict[str, str] = {}
        self._load_nhl_player_ids()

    def _load_nhl_player_ids(self):
        """Load NHL player IDs from file"""
        if not os.path.exists(self.player_ids_file):
            print(f"Warning: {self.player_ids_file} not found. Player IDs will not be mapped.")
            return

        with open(self.player_ids_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if ':' in line:
                    parts = line.rsplit(':', 1)
                    if len(parts) == 2:
                        name = parts[0].strip()
                        nhl_id = parts[1].strip()
                        self.nhl_player_ids[name] = nhl_id

        print(f"Loaded {len(self.nhl_player_ids)} NHL player ID mappings")

    def connect(self):
        """Connect to database"""
        self.conn = sqlite3.connect(self.db_path)
        self.cursor = self.conn.cursor()

    def disconnect(self):
        """Disconnect from database"""
        if self.conn:
            self.conn.close()
            self.conn = None
            self.cursor = None

    def __enter__(self):
        """Context manager entry"""
        self.connect()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit"""
        self.disconnect()

    def initialize_database(self, schema_path: str = "nhl_analytics_schema.sql"):
        """
        Initialize database with schema

        Args:
            schema_path: Path to SQL schema file
        """
        if not self.conn:
            raise RuntimeError("Not connected to database")

        with open(schema_path, 'r') as f:
            schema_sql = f.read()

        # Execute schema - split on semicolons but handle them in strings
        statements = schema_sql.split(';')
        for statement in statements:
            statement = statement.strip()
            if statement:
                try:
                    self.cursor.execute(statement)
                except sqlite3.Error as e:
                    print(f"Error executing statement: {e}")
                    print(f"Statement: {statement[:100]}...")

        self.conn.commit()
        print(f"Database initialized at {self.db_path}")

    def populate_reference_data(self):
        """Populate dimension tables with reference data"""
        if not self.conn:
            raise RuntimeError("Not connected to database")

        # Populate situations
        situations = [
            ('5v5', 'Five on Five', 'Five skaters per side'),
            ('All', 'All Situations', 'All game situations combined'),
            ('EV', 'Even Strength', 'All even strength situations'),
            ('PP', 'Power Play', 'Team has more skaters (typically 5v4)'),
            ('PK', 'Penalty Kill', 'Team has fewer skaters (typically 4v5)')
        ]

        for code, name, desc in situations:
            self.cursor.execute(
                "INSERT OR IGNORE INTO situations (situation_code, situation_name, description) VALUES (?, ?, ?)",
                (code, name, desc)
            )

        # Populate all NHL teams (2024-25 season) in alphabetical order by abbreviation
        # Note: Using abbreviations WITHOUT periods (N.J -> NJ, S.J -> SJ, etc.)
        nhl_teams = [
            ('ANA', 'Anaheim Ducks'),
            ('ARI', 'Arizona Coyotes'),
            ('BOS', 'Boston Bruins'),
            ('BUF', 'Buffalo Sabres'),
            ('CAR', 'Carolina Hurricanes'),
            ('CBJ', 'Columbus Blue Jackets'),
            ('CGY', 'Calgary Flames'),
            ('CHI', 'Chicago Blackhawks'),
            ('COL', 'Colorado Avalanche'),
            ('DAL', 'Dallas Stars'),
            ('DET', 'Detroit Red Wings'),
            ('EDM', 'Edmonton Oilers'),
            ('FLA', 'Florida Panthers'),
            ('LA', 'Los Angeles Kings'),
            ('MIN', 'Minnesota Wild'),
            ('MTL', 'Montreal Canadiens'),
            ('NJ', 'New Jersey Devils'),
            ('NSH', 'Nashville Predators'),
            ('NYI', 'New York Islanders'),
            ('NYR', 'New York Rangers'),
            ('OTT', 'Ottawa Senators'),
            ('PHI', 'Philadelphia Flyers'),
            ('PIT', 'Pittsburgh Penguins'),
            ('SJ', 'San Jose Sharks'),
            ('SEA', 'Seattle Kraken'),
            ('STL', 'St. Louis Blues'),
            ('TB', 'Tampa Bay Lightning'),
            ('TOR', 'Toronto Maple Leafs'),
            ('UTA', 'Utah Hockey Club'),
            ('VAN', 'Vancouver Canucks'),
            ('VGK', 'Vegas Golden Knights'),
            ('WPG', 'Winnipeg Jets'),
            ('WSH', 'Washington Capitals')
        ]

        for abbr, name in nhl_teams:
            self.cursor.execute(
                "INSERT OR IGNORE INTO teams (team_abbr, team_name) VALUES (?, ?)",
                (abbr, name)
            )

        self.conn.commit()
        print("Reference data populated")

        # Load situation map
        self.cursor.execute("SELECT situation_id, situation_code FROM situations")
        self.situation_map = {code: sid for sid, code in self.cursor.fetchall()}

        # Load team map
        self.cursor.execute("SELECT team_id, team_abbr FROM teams")
        self.team_map = {abbr: tid for tid, abbr in self.cursor.fetchall()}

    def get_or_create_team(self, team_abbr: str) -> int:
        """
        Get team ID from pre-populated teams table

        Args:
            team_abbr: Team abbreviation (e.g., 'OTT', 'BOS')

        Returns:
            Team ID
        """
        # Check cache first
        if team_abbr in self.team_map:
            return self.team_map[team_abbr]

        # Reload team map if not found
        self.cursor.execute("SELECT team_id, team_abbr FROM teams")
        self.team_map = {abbr: tid for tid, abbr in self.cursor.fetchall()}

        if team_abbr in self.team_map:
            return self.team_map[team_abbr]

        # This shouldn't happen if teams are pre-populated correctly
        raise ValueError(f"Team abbreviation '{team_abbr}' not found in teams table. Please add it to populate_reference_data().")

    def get_or_create_player(self, player_name: str, position: str) -> str:
        """
        Get player ID or create if doesn't exist

        Args:
            player_name: Player's name
            position: Player position (C, L, R, D, G)

        Returns:
            NHL Player ID (string)
        """
        # Normalize player name (replace non-breaking spaces with regular spaces)
        player_name = player_name.replace('\xa0', ' ').replace('\u00a0', ' ').strip()

        key = (player_name, position)
        if key in self.player_map:
            return self.player_map[key]

        # Get NHL player ID from mapping, or generate a placeholder
        nhl_player_id = self.nhl_player_ids.get(player_name)

        if not nhl_player_id:
            # If not found, create a placeholder ID (use negative numbers)
            nhl_player_id = f"UNKNOWN_{abs(hash(player_name)) % 1000000}"
            # Only print first few warnings to avoid spam
            if len([k for k in self.player_map.keys() if 'UNKNOWN' in str(self.player_map[k])]) < 5:
                print(f"Warning: No NHL ID found for '{player_name}' ({position}), using {nhl_player_id}")
                print(f"  Debug: Name length={len(player_name)}, repr={repr(player_name)}")

        # Try to get existing
        self.cursor.execute(
            "SELECT player_id FROM players WHERE player_id = ?",
            (nhl_player_id,)
        )
        result = self.cursor.fetchone()

        if not result:
            # Create new player
            self.cursor.execute(
                "INSERT INTO players (player_id, player_name, position) VALUES (?, ?, ?)",
                (nhl_player_id, player_name, position)
            )
            self.conn.commit()

        self.player_map[key] = nhl_player_id
        return nhl_player_id

    def get_or_create_game(self, game_info: GameInfo, game_date: str, season: str = None) -> str:
        """
        Get game ID or create if doesn't exist

        Args:
            game_info: Parsed game information
            game_date: Date of game (YYYY-MM-DD)
            season: Season string (e.g., '2024-2025')

        Returns:
            Game ID (TEXT - the actual NHL game ID)
        """
        game_id = game_info.nst_game_id

        # Try to get existing game
        self.cursor.execute(
            "SELECT game_id FROM games WHERE game_id = ?",
            (game_id,)
        )
        result = self.cursor.fetchone()

        if result:
            return result[0]

        # Create new game
        home_team_id = self.get_or_create_team(game_info.home_team)
        away_team_id = self.get_or_create_team(game_info.away_team)

        # Derive season from date if not provided
        if season is None:
            date_obj = datetime.strptime(game_date, '%Y-%m-%d')
            year = date_obj.year
            # NHL season spans two years, starts in October
            if date_obj.month >= 10:
                season = f"{year}-{year + 1}"
            else:
                season = f"{year - 1}-{year}"

        self.cursor.execute(
            """INSERT INTO games (game_id, home_team_id, away_team_id, game_date, season)
               VALUES (?, ?, ?, ?, ?)""",
            (game_id, home_team_id, away_team_id, game_date, season)
        )
        self.conn.commit()
        return game_id

    @staticmethod
    def parse_filename(filename: str) -> Optional[GameInfo]:
        """
        Parse CSV filename to extract game information

        Format: {AWAY}vs{HOME}_{GAMEID}_{TEAM}_{CATEGORY}_{SITUATION}.csv
        Example: BOSvsOTT_20149_Senators_Individual_5v5_1.csv

        Args:
            filename: CSV filename

        Returns:
            GameInfo object or None if parse fails
        """
        # Remove .csv extension
        name = filename.replace('.csv', '')

        # Pattern: {AWAY}vs{HOME}_{GAMEID}_{TEAM}_{CATEGORY}_{SITUATION}[_1|_2]
        # Updated to handle team abbrs with periods (N.J, S.J, L.A, T.B)
        pattern = r'^([A-Z][A-Z\.]+)vs([A-Z][A-Z\.]+)_(\d+)_([A-Za-z\.]+)_(.+?)_([A-Za-z0-9]+)(?:_([12]))?$'
        match = re.match(pattern, name)

        if not match:
            return None

        away, home, game_id, team, category_part, situation, file_type = match.groups()

        # Normalize team abbreviations (remove periods for consistency)
        # N.J -> NJ, S.J -> SJ, L.A -> LA, T.B -> TB
        away = away.replace('.', '')
        home = home.replace('.', '')
        team = team.replace('.', '')

        # Reconstruct category (may have underscores)
        # The category is everything between team name and situation
        # e.g., "Individual", "Forward_Lines", "On_Ice", "Shift_Report"
        return GameInfo(
            away_team=away,
            home_team=home,
            nst_game_id=game_id,
            team_name=team,
            category=category_part,
            situation=situation
        )

    @staticmethod
    def time_to_seconds(time_str: str) -> Optional[float]:
        """
        Convert time string to seconds

        Args:
            time_str: Time in format MM:SS or MM.decimal

        Returns:
            Time in seconds as float, or None if invalid
        """
        if not time_str or time_str == '-' or time_str == '':
            return None

        try:
            # Handle MM:SS format
            if ':' in time_str:
                parts = time_str.split(':')
                minutes = float(parts[0])
                seconds = float(parts[1]) if len(parts) > 1 else 0
                return minutes * 60 + seconds
            else:
                # Handle decimal minutes
                return float(time_str) * 60
        except (ValueError, AttributeError):
            return None

    @staticmethod
    def safe_float(value: Any) -> Optional[float]:
        """Safely convert value to float"""
        if value is None or value == '' or value == '-':
            return None
        try:
            return float(value)
        except (ValueError, TypeError):
            return None

    @staticmethod
    def safe_percentage(value: Any) -> Optional[float]:
        """
        Safely convert percentage value to decimal (0-1 scale)
        CSV percentages are stored as "XX.XX%" or "XX.XX", we convert to 0-1 for database
        """
        if value is None or value == '' or value == '-':
            return None
        try:
            # Remove '%' sign if present
            str_value = str(value).strip().replace('%', '')
            return float(str_value) / 100.0
        except (ValueError, TypeError):
            return None

    @staticmethod
    def safe_int(value: Any) -> int:
        """Safely convert value to int, return 0 if invalid"""
        if value is None or value == '' or value == '-':
            return 0
        try:
            return int(float(value))  # Handle "0.0" format
        except (ValueError, TypeError):
            return 0

    def import_player_stats(self, csv_path: str, game_id: str, team_id: int, situation_id: int):
        """
        Import individual player stats (skaters) from CSV

        Args:
            csv_path: Path to CSV file
            game_id: Game ID (TEXT - actual NHL game ID)
            team_id: Team ID
            situation_id: Situation ID
        """
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)

            for row in reader:
                player_name = row.get('Player', '').strip()
                position = row.get('Position', '').strip()

                if not player_name or not position:
                    continue

                player_id = self.get_or_create_player(player_name, position)

                # Parse all stats
                data = {
                    'game_id': game_id,
                    'player_id': player_id,
                    'team_id': team_id,
                    'situation_id': situation_id,
                    'toi_seconds': self.time_to_seconds(row.get('TOI', '')),
                    'goals': self.safe_int(row.get('Goals', 0)),
                    'total_assists': self.safe_int(row.get('Total Assists', 0)),
                    'first_assists': self.safe_int(row.get('First Assists', 0)),
                    'second_assists': self.safe_int(row.get('Second Assists', 0)),
                    'total_points': self.safe_int(row.get('Total Points', 0)),
                    'shots': self.safe_int(row.get('Shots', 0)),
                    'shooting_pct': self.safe_percentage(row.get('SH%', None)),
                    'ixg': self.safe_float(row.get('ixG', 0)),
                    'icf': self.safe_int(row.get('iCF', 0)),
                    'iscf': self.safe_int(row.get('iSCF', 0)),
                    'ihdcf': self.safe_int(row.get('iHDCF', 0)),
                    'rush_attempts': self.safe_int(row.get('Rush Attempts', 0)),
                    'rebound_attempts': self.safe_int(row.get('Rebound Attempts', 0)),
                    'rebounds_created': self.safe_int(row.get('Rebounds Created', 0)),
                    'pim': self.safe_int(row.get('PIM', 0)),
                    'total_penalties': self.safe_int(row.get('Total Penalties', 0)),
                    'minor_penalties': self.safe_int(row.get('Minor', 0)),
                    'major_penalties': self.safe_int(row.get('Major', 0)),
                    'misconduct_penalties': self.safe_int(row.get('Misconduct', 0)),
                    'penalties_drawn': self.safe_int(row.get('Penalties Drawn', 0)),
                    'giveaways': self.safe_int(row.get('Giveaways', 0)),
                    'takeaways': self.safe_int(row.get('Takeaways', 0)),
                    'hits': self.safe_int(row.get('Hits', 0)),
                    'hits_taken': self.safe_int(row.get('Hits Taken', 0)),
                    'shots_blocked': self.safe_int(row.get('Shots Blocked', 0)),
                    'faceoffs_won': self.safe_int(row.get('Faceoffs Won', 0)),
                    'faceoffs_lost': self.safe_int(row.get('Faceoffs Lost', 0)),
                    'faceoff_pct': self.safe_percentage(row.get('Faceoffs %', None))
                }

                # Insert or replace
                self.cursor.execute("""
                    INSERT OR REPLACE INTO player_game_stats (
                        game_id, player_id, team_id, situation_id,
                        toi_seconds, goals, total_assists, first_assists, second_assists, total_points,
                        shots, shooting_pct, ixg, icf, iscf, ihdcf,
                        rush_attempts, rebound_attempts, rebounds_created,
                        pim, total_penalties, minor_penalties, major_penalties, misconduct_penalties, penalties_drawn,
                        giveaways, takeaways, hits, hits_taken, shots_blocked,
                        faceoffs_won, faceoffs_lost, faceoff_pct
                    ) VALUES (
                        :game_id, :player_id, :team_id, :situation_id,
                        :toi_seconds, :goals, :total_assists, :first_assists, :second_assists, :total_points,
                        :shots, :shooting_pct, :ixg, :icf, :iscf, :ihdcf,
                        :rush_attempts, :rebound_attempts, :rebounds_created,
                        :pim, :total_penalties, :minor_penalties, :major_penalties, :misconduct_penalties, :penalties_drawn,
                        :giveaways, :takeaways, :hits, :hits_taken, :shots_blocked,
                        :faceoffs_won, :faceoffs_lost, :faceoff_pct
                    )
                """, data)

        self.conn.commit()

    def import_goalie_stats(self, csv_path: str, game_id: str, team_id: int, situation_id: int):
        """
        Import goaltender stats from CSV

        Args:
            csv_path: Path to CSV file
            game_id: Game ID (TEXT - actual NHL game ID)
            team_id: Team ID
            situation_id: Situation ID
        """
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)

            for row in reader:
                player_name = row.get('Player', '').strip()

                if not player_name:
                    continue

                player_id = self.get_or_create_player(player_name, 'G')

                data = {
                    'game_id': game_id,
                    'player_id': player_id,
                    'team_id': team_id,
                    'situation_id': situation_id,
                    'toi_seconds': self.time_to_seconds(row.get('TOI', '')),
                    'shots_against': self.safe_int(row.get('Shots Against', 0)),
                    'saves': self.safe_int(row.get('Saves', 0)),
                    'goals_against': self.safe_int(row.get('Goals Against', 0)),
                    'expected_goals_against': self.safe_float(row.get('Expected Goals Against', 0)),
                    'save_pct': self.safe_float(row.get('SV%', None)),  # Already in decimal format (0-1)
                    'gaa': self.safe_float(row.get('GAA', None)),
                    'hd_shots_against': self.safe_int(row.get('HD Shots Against', 0)),
                    'hd_saves': self.safe_int(row.get('HD Saves', 0)),
                    'hd_goals_against': self.safe_int(row.get('HD Goals Against', 0)),
                    'hd_save_pct': self.safe_float(row.get('HDSV%', None)),  # Already in decimal format (0-1)
                    'md_shots_against': self.safe_int(row.get('MD Shots Against', 0)),
                    'md_saves': self.safe_int(row.get('MD Saves', 0)),
                    'md_goals_against': self.safe_int(row.get('MD Goals Against', 0)),
                    'md_save_pct': self.safe_float(row.get('MDSV%', None)),  # Already in decimal format (0-1)
                    'ld_shots_against': self.safe_int(row.get('LD Shots Against', 0)),
                    'ld_saves': self.safe_int(row.get('LD Saves', 0)),
                    'ld_goals_against': self.safe_int(row.get('LD Goals Against', 0)),
                    'ld_save_pct': self.safe_float(row.get('LDSV%', None)),  # Already in decimal format (0-1)
                    'rush_shots_against': self.safe_int(row.get('Rush Shots Against', 0)),
                    'rebound_shots_against': self.safe_int(row.get('Rebound Shots Against', 0)),
                    'avg_shot_distance': self.safe_float(row.get('Avg. Shot Distance', None)),
                    'avg_goal_distance': self.safe_float(row.get('Avg. Goal Distance', None))
                }

                self.cursor.execute("""
                    INSERT OR REPLACE INTO goalie_game_stats (
                        game_id, player_id, team_id, situation_id,
                        toi_seconds, shots_against, saves, goals_against, expected_goals_against,
                        save_pct, gaa,
                        hd_shots_against, hd_saves, hd_goals_against, hd_save_pct,
                        md_shots_against, md_saves, md_goals_against, md_save_pct,
                        ld_shots_against, ld_saves, ld_goals_against, ld_save_pct,
                        rush_shots_against, rebound_shots_against,
                        avg_shot_distance, avg_goal_distance
                    ) VALUES (
                        :game_id, :player_id, :team_id, :situation_id,
                        :toi_seconds, :shots_against, :saves, :goals_against, :expected_goals_against,
                        :save_pct, :gaa,
                        :hd_shots_against, :hd_saves, :hd_goals_against, :hd_save_pct,
                        :md_shots_against, :md_saves, :md_goals_against, :md_save_pct,
                        :ld_shots_against, :ld_saves, :ld_goals_against, :ld_save_pct,
                        :rush_shots_against, :rebound_shots_against,
                        :avg_shot_distance, :avg_goal_distance
                    )
                """, data)

        self.conn.commit()

    def import_onice_stats(self, csv_path: str, game_id: str, team_id: int, situation_id: int):
        """Import on-ice stats from CSV"""
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)

            for row in reader:
                # Normalize column names - replace non-breaking spaces with regular spaces
                row = {k.replace('\xa0', ' ').replace('\u00a0', ' '): v for k, v in row.items()}

                player_name = row.get('Player', '').strip()
                position = row.get('Position', '').strip()

                if not player_name or not position:
                    continue

                player_id = self.get_or_create_player(player_name, position)

                data = {
                    'game_id': game_id,
                    'player_id': player_id,
                    'team_id': team_id,
                    'situation_id': situation_id,
                    'toi_seconds': self.time_to_seconds(row.get('TOI', '')),
                    'cf': self.safe_int(row.get('CF', 0)),
                    'ca': self.safe_int(row.get('CA', 0)),
                    'cf_pct': self.safe_percentage(row.get('CF%', None)),
                    'cf_pct_rel': self.safe_percentage(row.get('CF% Rel', None)),
                    'ff': self.safe_int(row.get('FF', 0)),
                    'fa': self.safe_int(row.get('FA', 0)),
                    'ff_pct': self.safe_percentage(row.get('FF%', None)),
                    'ff_pct_rel': self.safe_percentage(row.get('FF% Rel', None)),
                    'sf': self.safe_int(row.get('SF', 0)),
                    'sa': self.safe_int(row.get('SA', 0)),
                    'sf_pct': self.safe_percentage(row.get('SF%', None)),
                    'sf_pct_rel': self.safe_percentage(row.get('SF% Rel', None)),
                    'gf': self.safe_int(row.get('GF', 0)),
                    'ga': self.safe_int(row.get('GA', 0)),
                    'gf_pct': self.safe_percentage(row.get('GF%', None)),
                    'gf_pct_rel': self.safe_percentage(row.get('GF% Rel', None)),
                    'xgf': self.safe_float(row.get('xGF', 0)),
                    'xga': self.safe_float(row.get('xGA', 0)),
                    'xgf_pct': self.safe_percentage(row.get('xGF%', None)),
                    'xgf_pct_rel': self.safe_percentage(row.get('xGF% Rel', None)),
                    'scf': self.safe_int(row.get('SCF', 0)),
                    'sca': self.safe_int(row.get('SCA', 0)),
                    'scf_pct': self.safe_percentage(row.get('SCF%', None)),
                    'scf_pct_rel': self.safe_percentage(row.get('SCF% Rel', None)),
                    'hdcf': self.safe_int(row.get('HDCF', 0)),
                    'hdca': self.safe_int(row.get('HDCA', 0)),
                    'hdcf_pct': self.safe_percentage(row.get('HDCF%', None)),
                    'hdcf_pct_rel': self.safe_percentage(row.get('HDCF% Rel', None)),
                    'off_zone_shift_starts': self.safe_int(row.get('Off. Zone Shift Starts', 0)),
                    'neu_zone_shift_starts': self.safe_int(row.get('Neu. Zone Shift Starts', 0)),
                    'def_zone_shift_starts': self.safe_int(row.get('Def. Zone Shift Starts', 0)),
                    'otf_shift_starts': self.safe_int(row.get('On the Fly Shift Starts', 0)),
                    'off_zone_shift_start_pct': self.safe_percentage(row.get('Off. Zone Shift Start %', None)),
                    'off_zone_faceoffs': self.safe_int(row.get('Off. Zone Faceoffs', 0)),
                    'neu_zone_faceoffs': self.safe_int(row.get('Neu. Zone Faceoffs', 0)),
                    'def_zone_faceoffs': self.safe_int(row.get('Def. Zone Faceoffs', 0)),
                    'off_zone_faceoff_pct': self.safe_percentage(row.get('Off. Zone Faceoff %', None))
                }

                self.cursor.execute("""
                    INSERT OR REPLACE INTO player_onice_stats (
                        game_id, player_id, team_id, situation_id, toi_seconds,
                        cf, ca, cf_pct, cf_pct_rel,
                        ff, fa, ff_pct, ff_pct_rel,
                        sf, sa, sf_pct, sf_pct_rel,
                        gf, ga, gf_pct, gf_pct_rel,
                        xgf, xga, xgf_pct, xgf_pct_rel,
                        scf, sca, scf_pct, scf_pct_rel,
                        hdcf, hdca, hdcf_pct, hdcf_pct_rel,
                        off_zone_shift_starts, neu_zone_shift_starts, def_zone_shift_starts, otf_shift_starts,
                        off_zone_shift_start_pct,
                        off_zone_faceoffs, neu_zone_faceoffs, def_zone_faceoffs, off_zone_faceoff_pct
                    ) VALUES (
                        :game_id, :player_id, :team_id, :situation_id, :toi_seconds,
                        :cf, :ca, :cf_pct, :cf_pct_rel,
                        :ff, :fa, :ff_pct, :ff_pct_rel,
                        :sf, :sa, :sf_pct, :sf_pct_rel,
                        :gf, :ga, :gf_pct, :gf_pct_rel,
                        :xgf, :xga, :xgf_pct, :xgf_pct_rel,
                        :scf, :sca, :scf_pct, :scf_pct_rel,
                        :hdcf, :hdca, :hdcf_pct, :hdcf_pct_rel,
                        :off_zone_shift_starts, :neu_zone_shift_starts, :def_zone_shift_starts, :otf_shift_starts,
                        :off_zone_shift_start_pct,
                        :off_zone_faceoffs, :neu_zone_faceoffs, :def_zone_faceoffs, :off_zone_faceoff_pct
                    )
                """, data)

        self.conn.commit()

    def import_shift_stats(self, csv_path: str, game_id: str, team_id: int, situation_id: int):
        """Import shift report stats from CSV"""
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)

            for row in reader:
                player_name = row.get('Player', '').strip()
                position = row.get('Position', '').strip()

                if not player_name or not position:
                    continue

                # Skip summary rows (Forwards, Defense)
                if player_name in ['Forwards', 'Defense']:
                    continue

                player_id = self.get_or_create_player(player_name, position)

                data = {
                    'game_id': game_id,
                    'player_id': player_id,
                    'team_id': team_id,
                    'situation_id': situation_id,
                    'toi_seconds': self.time_to_seconds(row.get('TOI', '')),
                    'shifts': self.safe_int(row.get('Shifts', 0)),
                    'avg_shift_length': self.safe_float(row.get('Avg. Shift Length', None)),
                    'shift_std_dev': self.safe_float(row.get('Standard Deviation', None)),
                    'short_shifts': self.safe_int(row.get('Short Shifts', 0)),
                    'long_shifts': self.safe_int(row.get('Long Shifts', 0)),
                    'extra_short_shifts': self.safe_int(row.get('Extra Short', 0)),
                    'extra_long_shifts': self.safe_int(row.get('Extra Long', 0))
                }

                self.cursor.execute("""
                    INSERT OR REPLACE INTO player_shift_stats (
                        game_id, player_id, team_id, situation_id, toi_seconds,
                        shifts, avg_shift_length, shift_std_dev,
                        short_shifts, long_shifts, extra_short_shifts, extra_long_shifts
                    ) VALUES (
                        :game_id, :player_id, :team_id, :situation_id, :toi_seconds,
                        :shifts, :avg_shift_length, :shift_std_dev,
                        :short_shifts, :long_shifts, :extra_short_shifts, :extra_long_shifts
                    )
                """, data)

        self.conn.commit()

    def import_forward_lines(self, csv_path: str, game_id: str, team_id: int, situation_id: int):
        """Import forward line combination stats from CSV"""
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)

            for row in reader:
                # Normalize column names - replace non-breaking spaces with regular spaces
                row = {k.replace('\xa0', ' ').replace('\u00a0', ' '): v for k, v in row.items()}

                p1 = row.get('Player 1', '').strip()
                p2 = row.get('Player 2', '').strip()
                p3 = row.get('Player 3', '').strip()

                if not p1 or not p2 or not p3:
                    continue

                # Get player IDs (assume forward position for line combos)
                p1_id = self.get_or_create_player(p1, 'F')
                p2_id = self.get_or_create_player(p2, 'F')
                p3_id = self.get_or_create_player(p3, 'F')

                data = {
                    'game_id': game_id,
                    'team_id': team_id,
                    'situation_id': situation_id,
                    'player1_id': p1_id,
                    'player2_id': p2_id,
                    'player3_id': p3_id,
                    'toi_seconds': self.time_to_seconds(row.get('TOI', '')),
                    'cf': self.safe_int(row.get('CF', 0)),
                    'ca': self.safe_int(row.get('CA', 0)),
                    'cf_pct': self.safe_percentage(row.get('CF%', None)),
                    'cf_pct_rel': self.safe_percentage(row.get('CF% Rel', None)),
                    'ff': self.safe_int(row.get('FF', 0)),
                    'fa': self.safe_int(row.get('FA', 0)),
                    'ff_pct': self.safe_percentage(row.get('FF%', None)),
                    'ff_pct_rel': self.safe_percentage(row.get('FF% Rel', None)),
                    'sf': self.safe_int(row.get('SF', 0)),
                    'sa': self.safe_int(row.get('SA', 0)),
                    'sf_pct': self.safe_percentage(row.get('SF%', None)),
                    'sf_pct_rel': self.safe_percentage(row.get('SF% Rel', None)),
                    'gf': self.safe_int(row.get('GF', 0)),
                    'ga': self.safe_int(row.get('GA', 0)),
                    'gf_pct': self.safe_percentage(row.get('GF%', None)),
                    'gf_pct_rel': self.safe_percentage(row.get('GF% Rel', None)),
                    'xgf': self.safe_float(row.get('xGF', 0)),
                    'xga': self.safe_float(row.get('xGA', 0)),
                    'xgf_pct': self.safe_percentage(row.get('xGF%', None)),
                    'xgf_pct_rel': self.safe_percentage(row.get('xGF% Rel', None)),
                    'scf': self.safe_int(row.get('SCF', 0)),
                    'sca': self.safe_int(row.get('SCA', 0)),
                    'scf_pct': self.safe_percentage(row.get('SCF%', None)),
                    'scf_pct_rel': self.safe_percentage(row.get('SCF% Rel', None)),
                    'hdcf': self.safe_int(row.get('HDCF', 0)),
                    'hdca': self.safe_int(row.get('HDCA', 0)),
                    'hdcf_pct': self.safe_percentage(row.get('HDCF%', None)),
                    'hdcf_pct_rel': self.safe_percentage(row.get('HDCF% Rel', None)),
                    'rush_attempts_for': self.safe_int(row.get('Rush Attempts For', 0)),
                    'rush_attempts_against': self.safe_int(row.get('Rush Attempts Against', 0)),
                    'rush_attempt_pct': self.safe_percentage(row.get('Rush Attempt %', None)),
                    'rush_attempt_pct_rel': self.safe_percentage(row.get('Rush Attempt % Rel', None)),
                    'rebound_attempts_for': self.safe_int(row.get('Rebound Attempts For', 0)),
                    'rebound_attempts_against': self.safe_int(row.get('Rebound Attempts Against', 0)),
                    'rebound_attempt_pct': self.safe_percentage(row.get('Rebound Attempt %', None)),
                    'rebound_attempt_pct_rel': self.safe_percentage(row.get('Rebound Attempt % Rel', None)),
                    'off_zone_faceoffs': self.safe_int(row.get('Off. Zone Faceoffs', 0)),
                    'neu_zone_faceoffs': self.safe_int(row.get('Neu. Zone Faceoffs', 0)),
                    'def_zone_faceoffs': self.safe_int(row.get('Def. Zone Faceoffs', 0)),
                    'off_zone_faceoff_pct': self.safe_percentage(row.get('Off. Zone Faceoff %', None))
                }

                self.cursor.execute("""
                    INSERT OR REPLACE INTO line_combinations (
                        game_id, team_id, situation_id, player1_id, player2_id, player3_id,
                        toi_seconds,
                        cf, ca, cf_pct, cf_pct_rel,
                        ff, fa, ff_pct, ff_pct_rel,
                        sf, sa, sf_pct, sf_pct_rel,
                        gf, ga, gf_pct, gf_pct_rel,
                        xgf, xga, xgf_pct, xgf_pct_rel,
                        scf, sca, scf_pct, scf_pct_rel,
                        hdcf, hdca, hdcf_pct, hdcf_pct_rel,
                        rush_attempts_for, rush_attempts_against, rush_attempt_pct, rush_attempt_pct_rel,
                        rebound_attempts_for, rebound_attempts_against, rebound_attempt_pct, rebound_attempt_pct_rel,
                        off_zone_faceoffs, neu_zone_faceoffs, def_zone_faceoffs, off_zone_faceoff_pct
                    ) VALUES (
                        :game_id, :team_id, :situation_id, :player1_id, :player2_id, :player3_id,
                        :toi_seconds,
                        :cf, :ca, :cf_pct, :cf_pct_rel,
                        :ff, :fa, :ff_pct, :ff_pct_rel,
                        :sf, :sa, :sf_pct, :sf_pct_rel,
                        :gf, :ga, :gf_pct, :gf_pct_rel,
                        :xgf, :xga, :xgf_pct, :xgf_pct_rel,
                        :scf, :sca, :scf_pct, :scf_pct_rel,
                        :hdcf, :hdca, :hdcf_pct, :hdcf_pct_rel,
                        :rush_attempts_for, :rush_attempts_against, :rush_attempt_pct, :rush_attempt_pct_rel,
                        :rebound_attempts_for, :rebound_attempts_against, :rebound_attempt_pct, :rebound_attempt_pct_rel,
                        :off_zone_faceoffs, :neu_zone_faceoffs, :def_zone_faceoffs, :off_zone_faceoff_pct
                    )
                """, data)

        self.conn.commit()

    def import_team_overview(self, csv_path: str, game_id: str, team_id: int, situation_id: int):
        """Import team overview stats (period by period) from CSV"""
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)

            for row in reader:
                period_str = row.get('Period', '').strip()

                if not period_str:
                    continue

                # Map period string to number (1, 2, 3, or 0 for Final)
                period_map = {'1': 1, '2': 2, '3': 3, 'Final': 0}
                period = period_map.get(period_str, None)

                if period is None:
                    continue

                data = {
                    'game_id': game_id,
                    'team_id': team_id,
                    'situation_id': situation_id,
                    'period': period,
                    'toi_seconds': self.time_to_seconds(row.get('TOI', '')),
                    'cf': self.safe_float(row.get('CF', 0)),
                    'ca': self.safe_float(row.get('CA', 0)),
                    'cf_pct': self.safe_percentage(row.get('CF%', None)),
                    'ff': self.safe_float(row.get('FF', 0)),
                    'fa': self.safe_float(row.get('FA', 0)),
                    'ff_pct': self.safe_percentage(row.get('FF%', None)),
                    'sf': self.safe_float(row.get('SF', 0)),
                    'sa': self.safe_float(row.get('SA', 0)),
                    'sf_pct': self.safe_percentage(row.get('SF%', None)),
                    'scf': self.safe_float(row.get('SCF', 0)),
                    'sca': self.safe_float(row.get('SCA', 0)),
                    'scf_pct': self.safe_percentage(row.get('SCF%', None)),
                    'hdcf': self.safe_float(row.get('HDCF', 0)),
                    'hdca': self.safe_float(row.get('HDCA', 0)),
                    'hdcf_pct': self.safe_percentage(row.get('HDCF%', None)),
                    'xgf': self.safe_float(row.get('xGF', 0)),
                    'xga': self.safe_float(row.get('xGA', 0)),
                    'xgf_pct': self.safe_percentage(row.get('xGF%', None)),
                    'gf': self.safe_float(row.get('GF', 0)),
                    'ga': self.safe_float(row.get('GA', 0)),
                    'gf_pct': self.safe_percentage(row.get('GF%', None))
                }

                self.cursor.execute("""
                    INSERT OR REPLACE INTO team_game_overview (
                        game_id, team_id, situation_id, period, toi_seconds,
                        cf, ca, cf_pct,
                        ff, fa, ff_pct,
                        sf, sa, sf_pct,
                        scf, sca, scf_pct,
                        hdcf, hdca, hdcf_pct,
                        xgf, xga, xgf_pct,
                        gf, ga, gf_pct
                    ) VALUES (
                        :game_id, :team_id, :situation_id, :period, :toi_seconds,
                        :cf, :ca, :cf_pct,
                        :ff, :fa, :ff_pct,
                        :sf, :sa, :sf_pct,
                        :scf, :sca, :scf_pct,
                        :hdcf, :hdca, :hdcf_pct,
                        :xgf, :xga, :xgf_pct,
                        :gf, :ga, :gf_pct
                    )
                """, data)

        self.conn.commit()

    def import_csv_file(self, csv_path: str, game_date: str, team_abbr: str = None):
        """
        Import a single CSV file into the database

        Args:
            csv_path: Path to CSV file
            game_date: Date of game (YYYY-MM-DD format)
            team_abbr: Team abbreviation (extracted from directory path)
        """
        filename = os.path.basename(csv_path)
        game_info = self.parse_filename(filename)

        if not game_info:
            print(f"Could not parse filename: {filename}")
            return

        # Skip aggregate opponent stats files (e.g., ANAvsOPP_*)
        if game_info.home_team == 'OPP' or game_info.away_team == 'OPP':
            return  # Silently skip OPP aggregate files

        # Extract team abbreviation from path if not provided
        if team_abbr is None:
            # Path format: nhlteamreports/OTT/games/2025-11-01/...
            path_parts = Path(csv_path).parts
            if 'nhlteamreports' in path_parts:
                idx = path_parts.index('nhlteamreports')
                if idx + 1 < len(path_parts):
                    team_abbr = path_parts[idx + 1]

        if not team_abbr:
            print(f"Could not determine team abbreviation for: {csv_path}")
            return

        # Get IDs
        game_id = self.get_or_create_game(game_info, game_date)
        team_id = self.get_or_create_team(team_abbr)
        situation_id = self.situation_map.get(game_info.situation)

        if situation_id is None:
            print(f"Unknown situation: {game_info.situation}")
            return

        # Determine file type and import accordingly
        category = game_info.category

        # Check if it's a _1 or _2 file
        is_goalie_file = filename.endswith('_2.csv')
        is_player_file = filename.endswith('_1.csv')

        if 'Individual' in category:
            if is_goalie_file:
                self.import_goalie_stats(csv_path, game_id, team_id, situation_id)
            elif is_player_file:
                self.import_player_stats(csv_path, game_id, team_id, situation_id)
        elif 'On' in category and 'Ice' in category:
            self.import_onice_stats(csv_path, game_id, team_id, situation_id)
        elif 'Shift' in category:
            self.import_shift_stats(csv_path, game_id, team_id, situation_id)
        elif 'Forward' in category and 'Lines' in category:
            self.import_forward_lines(csv_path, game_id, team_id, situation_id)
        elif 'overview' in category:
            self.import_team_overview(csv_path, game_id, team_id, situation_id)

    def _load_game_dates_from_list(self, games_list_path: str) -> Dict[str, str]:
        """
        Load game dates from {TEAM}_games_list.csv file

        Args:
            games_list_path: Path to games list CSV

        Returns:
            Dictionary mapping game_id to game_date (YYYY-MM-DD)
        """
        game_dates = {}

        if not os.path.exists(games_list_path):
            return game_dates

        with open(games_list_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                game_id = row.get('game_id', '').strip()
                game_date = row.get('date', '').strip()

                if game_id and game_date:
                    game_dates[game_id] = game_date

        return game_dates

    def import_team_directory(self, team_dir: str):
        """
        Import all CSV files for a team

        Args:
            team_dir: Path to team directory (e.g., nhlteamreports/OTT)
        """
        # Load situation map if not loaded
        if not self.situation_map:
            self.cursor.execute("SELECT situation_id, situation_code FROM situations")
            self.situation_map = {code: sid for sid, code in self.cursor.fetchall()}

        games_dir = Path(team_dir) / 'games'

        if not games_dir.exists():
            print(f"Games directory not found: {games_dir}")
            return

        # Extract team abbreviation from path
        team_abbr = Path(team_dir).name

        # Iterate through season folders (e.g., "2024-25", "2025-26")
        for season_dir in sorted(games_dir.iterdir()):
            if not season_dir.is_dir():
                continue

            season_name = season_dir.name  # e.g., "2024-25"
            print(f"\nProcessing season {season_name}...")

            # Load game dates from games list CSV
            games_list_path = season_dir / f"{team_abbr}_games_list.csv"
            game_dates_map = self._load_game_dates_from_list(str(games_list_path))

            if not game_dates_map:
                print(f"Warning: Could not load game dates from {games_list_path}")
                print(f"Skipping season {season_name}")
                continue

            # Import all CSV files in this season (except games_list)
            csv_files = [f for f in season_dir.glob('*.csv') if 'games_list' not in f.name]

            for csv_file in csv_files:
                try:
                    # Parse filename to get game ID
                    game_info = self.parse_filename(csv_file.name)
                    if not game_info:
                        print(f"Could not parse filename: {csv_file.name}")
                        continue

                    # Look up game date
                    game_date = game_dates_map.get(game_info.nst_game_id)

                    if not game_date:
                        print(f"Warning: No date found for game {game_info.nst_game_id} in {csv_file.name}")
                        continue

                    self.import_csv_file(str(csv_file), game_date)
                except Exception as e:
                    print(f"Error importing {csv_file.name}: {e}")

            print(f"Imported {len(csv_files)} files for {season_name}")

    def import_all_teams(self, base_dir: str = 'nhlteamreports'):
        """
        Import all teams from the base directory

        Args:
            base_dir: Base directory containing team folders
        """
        base_path = Path(base_dir)

        if not base_path.exists():
            print(f"Base directory not found: {base_dir}")
            return

        # Get all team directories
        team_dirs = [d for d in base_path.iterdir() if d.is_dir()]

        print(f"Found {len(team_dirs)} team directories")

        for team_dir in sorted(team_dirs):
            print(f"\n{'='*60}")
            print(f"Processing team: {team_dir.name}")
            print(f"{'='*60}")
            self.import_team_directory(str(team_dir))

        print("\n" + "="*60)
        print("Import complete!")
        print("="*60)


def main():
    """Main entry point"""
    import argparse
    import os

    parser = argparse.ArgumentParser(description='NHL Analytics Database Manager')
    parser.add_argument('--init', action='store_true', help='Initialize database')
    parser.add_argument('--import-all', action='store_true', help='Import all teams')
    parser.add_argument('--import-team', type=str, help='Import specific team (team abbr)')
    parser.add_argument('--db', type=str, default='nhl_analytics.db', help='Database path')
    parser.add_argument('--schema', type=str, default='nhl_analytics_schema.sql', help='Schema file path')

    args = parser.parse_args()

    # If no flags provided, auto-init if DB doesn't exist, then import all
    if not args.init and not args.import_all and not args.import_team:
        args.init = not os.path.exists(args.db)
        args.import_all = True

    with NHLDatabaseManager(args.db) as db:
        if args.init:
            print("Initializing database...")
            db.initialize_database(args.schema)
            db.populate_reference_data()

        if args.import_all:
            print("Importing all teams...")
            db.import_all_teams()

        if args.import_team:
            team_dir = f"nhlteamreports/{args.import_team}"
            print(f"Importing team: {args.import_team}")
            db.import_team_directory(team_dir)


if __name__ == '__main__':
    main()
