# TODO: use this to verify that dan's attempt has all of them and doesn't contain duplicates or hallucinations
abbrevlist = ["afa", "aic", "aka", "akf", "arm", "asu", "aug", "bc_", "ben", "bgs", "bmj", "brn", "bu_", "cc_", "clg", "clk", "cns", "con", "cor", "dar", "den", "fsu", "har", "hcr", "lin", "liu", "lss", "mer", "mia", "mic", "min", "mnd", "mne", "mns", "mrc", "msu", "mtu", "ndk", "ndm", "nia", "nmu", "noe", "osu", "prn", "prv", "psu", "qui", "ren", "rit", "rmu", "sac", "stc", "stl", "stn", "stt", "uma", "uml", "unh", "uni", "uno", "ver", "wis", "wmu", "yal",]

# DAN's attempt:
# TODO: double-check this
dans_teamabbrevs = {
    1: "afa",
    5: "aic",
    3: "aka",
    4: "akf",
    6: "arm",
    61: "asu",
    64: "aug",
    9: "bc_",
    8: "ben",
    11: "bgs",
    7: "bmj",
    12: "brn",
    10: "bu_",
    16: "cc_",
    15: "clg",
    14: "clk",
    13: "cns",
    17: "con",
    18: "cor",
    19: "dar",
    20: "den",
    21: "fsu",
    22: "har",
    23: "hcr",
    433: "lin",
    62: "liu",
    24: "lss",
    29: "mer",
    30: "mia",
    31: "mic",
    34: "min",
    36: "mnd",
    25: "mne",
    35: "mns",
    28: "mrc",
    32: "msu",
    33: "mtu",
    40: "ndk",
    43: "ndm",
    39: "nia",
    42: "nmu",
    41: "noe",
    44: "osu",
    45: "prn",
    46: "prv",
    60: "psu",
    47: "qui",
    48: "ren",
    49: "rit",
    50: "rmu",
    51: "sac",
    52: "stc",
    53: "stl",
    422: "stn",
    63: "stt",
    27: "uma",
    26: "uml",
    38: "unh",
    54: "uni",
    37: "uno",
    55: "ver",
    58: "wis",
    57: "wmu",
    59: "yal"
}


# convenience function to also perform lookup from name to ID
def NameToAbbrev(name):
    pass


# Dan's attempt to associate abbrevs with team names
maybeuseful = {
    "afa": "Air-Force",
    "aic": "American-Intl",
    "aka": "Alaska-Anchorage",
    "akf": "Alaska",
    "arm": "Army",
    "asu": "Arizona-State",
    "aug": "Augustana",
    "bc_": "Boston-College",
    "ben": "Bentley",
    "bgs": "Bowling-Green",
    "bmj": "Bemidji-State",
    "brn": "Brown",
    "bu_": "Boston-University",
    "cc_": "Colorado-College",
    "clg": "Colgate",
    "clk": "Clarkson",
    "cns": "Canisius",
    "con": "Connecticut",
    "cor": "Cornell",
    "dar": "Dartmouth",
    "den": "Denver",
    "fsu": "Ferris-State",
    "har": "Harvard",
    "hcr": "Holy-Cross",
    "lin": "Lindenwood",
    "liu": "Long-Island",
    "lss": "Lake-Superior",
    "mer": "Merrimack",
    "mia": "Miami",
    "mic": "Michigan",
    "min": "Minnesota",
    "mnd": "Minnesota-Duluth",
    "mne": "Maine",
    "mns": "Minnesota-State",
    "mrc": "Mercyhurst",
    "msu": "Michigan-State",
    "mtu": "Michigan-Tech",
    "ndk": "North-Dakota",
    "ndm": "Notre-Dame",
    "nia": "Niagara",
    "nmu": "Northern-Michigan",
    "noe": "Northeastern",
    "osu": "Ohio-State",
    "prn": "Princeton",
    "prv": "Providence",
    "psu": "Penn-State",
    "qui": "Quinnipiac",
    "ren": "Rensselaer",
    "rit": "RIT",
    "rmu": "Robert-Morris",
    "sac": "Sacred-Heart",
    "stc": "St-Cloud-State",
    "stl": "St-Lawrence",
    "stn": "Stonehill",
    "stt": "St-Thomas",
    "uma": "Massachusetts",
    "uml": "UMass-Lowell",
    "unh": "New-Hampshire",
    "uni": "Union",
    "uno": "Nebraska-Omaha",
    "ver": "Vermont",
    "wis": "Wisconsin",
    "wmu": "Western-Michigan",
    "yal": "Yale"
}
